#######################################################
#       Build BLE adapter for Android
#######################################################

Import('env', 'src_dir')
import os.path

env.PrependUnique(CPPPATH = [ os.path.join(src_dir, 'android') ])

src_files = [ 'caleclient.c',
              'caleserver.c',
              'calenwmonitor.c',
              'caleutils.c' ]

Return('src_files')
