# //******************************************************************
# //
# // Copyright 2015 Samsung Electronics All Rights Reserved.
# //
# //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# //
# // Licensed under the Apache License, Version 2.0 (the "License");
# // you may not use this file except in compliance with the License.
# // You may obtain a copy of the License at
# //
# //      http://www.apache.org/licenses/LICENSE-2.0
# //
# // Unless required by applicable law or agreed to in writing, software
# // distributed under the License is distributed on an "AS IS" BASIS,
# // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# // See the License for the specific language governing permissions and
# // limitations under the License.
# //
# //-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# SConscript file for Local PKI google tests

Import('env')

import os
import os.path
tools_env = env.Clone()

src_dir = tools_env.get('SRC_DIR')

######################################################################
# Build flags
######################################################################
tools_env.PrependUnique(CPPPATH = [
        '../include/',
        '../../../../../../extlibs/asn1cert',
        '../../../../../../extlibs/tinydtls/ecc',
         '../../../../../../extlibs/tinydtls/sha2',
         '../../../../connectivity/inc/pkix/'
		])
tools_env.AppendUnique(LIBPATH = [env.get('BUILD_DIR')])

tools_env.AppendUnique(LIBS = ['CKManager'])
tools_env.AppendUnique(LIBS = ['asn1'])
tools_env.AppendUnique(LIBS = ['octbstack'])
tools_env.AppendUnique(LIBS = ['tinydtls'])
tools_env.AppendUnique(LIBS = ['connectivity_abstraction'])

if not env.get('RELEASE'):
	tools_env.AppendUnique(CPPDEFINES = ['X509_DEBUG'])

######################################################################
# Source files and Targets
######################################################################
x509_check = tools_env.Program('x509_check', ['x509_check.c'])
x509_issue = tools_env.Program('x509_issue', ['x509_issue.c'])



