//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

using namespace concurrency;

namespace com { namespace microsoft { namespace OICBridge { namespace oic { namespace r { namespace light { namespace brightness {

ref class brightnessConsumer;

public ref class brightnessJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property brightnessConsumer^ Consumer
    {
        brightnessConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ brightnessConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    brightnessConsumer^ m_consumer;
};

public ref class brightnessGetValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property int64 Value
    {
        int64 get() { return m_value; }
    internal:
        void set(_In_ int64 value) { m_value = value; }
    }

    static brightnessGetValueResult^ CreateSuccessResult(_In_ int64 value)
    {
        auto result = ref new brightnessGetValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Value = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static brightnessGetValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new brightnessGetValueResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    int64 m_value;
};

public ref class brightnessSetValueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static brightnessSetValueResult^ CreateSuccessResult()
    {
        auto result = ref new brightnessSetValueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static brightnessSetValueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new brightnessSetValueResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

} } } } } } } 
