//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Foundation;
using namespace Windows::Foundation::Collections;
using namespace Windows::Devices::AllJoyn;
using namespace com::microsoft::OICBridge::oic::r::airflow;

// Note: Unlike an Interface implementation, which provides a single handler for each member, the event
// model allows for 0 or more listeners to be registered. The EventAdapter implementation deals with this
// difference by implementing a last-writer-wins policy. The lack of any return value (i.e., 0 listeners)
// is handled by returning a null result.

// Methods
// Property Reads
IAsyncOperation<airflowGetDirectionResult^>^ airflowServiceEventAdapter::GetDirectionAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new airflowGetDirectionRequestedEventArgs(info);
    AllJoynHelpers::DispatchEvent([=]() {
        GetDirectionRequested(this, args);
    });
    return airflowGetDirectionRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<airflowGetRangeResult^>^ airflowServiceEventAdapter::GetRangeAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new airflowGetRangeRequestedEventArgs(info);
    AllJoynHelpers::DispatchEvent([=]() {
        GetRangeRequested(this, args);
    });
    return airflowGetRangeRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<airflowGetSpeedResult^>^ airflowServiceEventAdapter::GetSpeedAsync(_In_ AllJoynMessageInfo^ info)
{
    auto args = ref new airflowGetSpeedRequestedEventArgs(info);
    AllJoynHelpers::DispatchEvent([=]() {
        GetSpeedRequested(this, args);
    });
    return airflowGetSpeedRequestedEventArgs::GetResultAsync(args);
}

// Property Writes
IAsyncOperation<airflowSetDirectionResult^>^ airflowServiceEventAdapter::SetDirectionAsync(_In_ AllJoynMessageInfo^ info, _In_ Platform::String^ value)
{
    auto args = ref new airflowSetDirectionRequestedEventArgs(info, value);
    AllJoynHelpers::DispatchEvent([=]() {
        SetDirectionRequested(this, args);
    });
    return airflowSetDirectionRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<airflowSetRangeResult^>^ airflowServiceEventAdapter::SetRangeAsync(_In_ AllJoynMessageInfo^ info, _In_ Platform::String^ value)
{
    auto args = ref new airflowSetRangeRequestedEventArgs(info, value);
    AllJoynHelpers::DispatchEvent([=]() {
        SetRangeRequested(this, args);
    });
    return airflowSetRangeRequestedEventArgs::GetResultAsync(args);
}

IAsyncOperation<airflowSetSpeedResult^>^ airflowServiceEventAdapter::SetSpeedAsync(_In_ AllJoynMessageInfo^ info, _In_ int64 value)
{
    auto args = ref new airflowSetSpeedRequestedEventArgs(info, value);
    AllJoynHelpers::DispatchEvent([=]() {
        SetSpeedRequested(this, args);
    });
    return airflowSetSpeedRequestedEventArgs::GetResultAsync(args);
}

