#******************************************************************
#
# Copyright 2015 Intel Mobile Communications GmbH All Rights Reserved.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
##
# Plugin Interface build script
##

import os.path

Import('env')

target_os = env.get('TARGET_OS')
build_sample = env.get('BUILD_SAMPLE')
src_dir = env.get('SRC_DIR')

if target_os not in ['android', 'arduino', 'darwin', 'ios']:

    SConscript(os.path.join('zigbee_wrapper', 'SConscript'))

    SConscript(os.path.join('src', 'SConscript'))

    SConscript(os.path.join('unittests', 'SConscript'))

    if build_sample == 'ON':
	    if target_os in ['linux']:
		    target_path = target_os
		    SConscript(os.path.join('samples', target_path, 'SConscript'))

