//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace alljoyn { namespace Control { namespace Volume {

public interface class IVolumeService
{
public:
    // Implement this function to handle calls to the AdjustVolume method.
    Windows::Foundation::IAsyncOperation<VolumeAdjustVolumeResult^>^ AdjustVolumeAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ int16 interfaceMemberDelta);

    // Implement this function to handle calls to the AdjustVolumePercent method.
    Windows::Foundation::IAsyncOperation<VolumeAdjustVolumePercentResult^>^ AdjustVolumePercentAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ double interfaceMemberChange);

    // Implement this function to handle requests for the value of the Enabled property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<VolumeGetEnabledResult^>^ GetEnabledAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests for the value of the Mute property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<VolumeGetMuteResult^>^ GetMuteAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the Mute property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<VolumeSetMuteResult^>^ SetMuteAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, bool value);

    // Implement this function to handle requests for the value of the Version property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<VolumeGetVersionResult^>^ GetVersionAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests for the value of the Volume property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<VolumeGetVolumeResult^>^ GetVolumeAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    // Implement this function to handle requests to set the Volume property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<VolumeSetVolumeResult^>^ SetVolumeAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, int16 value);

    // Implement this function to handle requests for the value of the VolumeRange property.
    //
    // Currently, info will always be null, because no information is available about the requestor.
    Windows::Foundation::IAsyncOperation<VolumeGetVolumeRangeResult^>^ GetVolumeRangeAsync(Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

};

} } } } 
