//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

using namespace concurrency;

namespace org { namespace alljoyn { namespace Control { namespace Volume {

ref class VolumeConsumer;

public ref class VolumeAdjustVolumeResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static VolumeAdjustVolumeResult^ CreateSuccessResult()
    {
        auto result = ref new VolumeAdjustVolumeResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static VolumeAdjustVolumeResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new VolumeAdjustVolumeResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class VolumeAdjustVolumePercentResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static VolumeAdjustVolumePercentResult^ CreateSuccessResult()
    {
        auto result = ref new VolumeAdjustVolumePercentResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static VolumeAdjustVolumePercentResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new VolumeAdjustVolumePercentResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class VolumeJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property VolumeConsumer^ Consumer
    {
        VolumeConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ VolumeConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    VolumeConsumer^ m_consumer;
};

public ref class VolumeGetEnabledResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool Enabled
    {
        bool get() { return m_value; }
    internal:
        void set(_In_ bool value) { m_value = value; }
    }

    static VolumeGetEnabledResult^ CreateSuccessResult(_In_ bool value)
    {
        auto result = ref new VolumeGetEnabledResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Enabled = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static VolumeGetEnabledResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new VolumeGetEnabledResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    bool m_value;
};

public ref class VolumeGetMuteResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool Mute
    {
        bool get() { return m_value; }
    internal:
        void set(_In_ bool value) { m_value = value; }
    }

    static VolumeGetMuteResult^ CreateSuccessResult(_In_ bool value)
    {
        auto result = ref new VolumeGetMuteResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Mute = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static VolumeGetMuteResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new VolumeGetMuteResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    bool m_value;
};

public ref class VolumeSetMuteResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static VolumeSetMuteResult^ CreateSuccessResult()
    {
        auto result = ref new VolumeSetMuteResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static VolumeSetMuteResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new VolumeSetMuteResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class VolumeGetVersionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint16 Version
    {
        uint16 get() { return m_value; }
    internal:
        void set(_In_ uint16 value) { m_value = value; }
    }

    static VolumeGetVersionResult^ CreateSuccessResult(_In_ uint16 value)
    {
        auto result = ref new VolumeGetVersionResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Version = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static VolumeGetVersionResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new VolumeGetVersionResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint16 m_value;
};

public ref class VolumeGetVolumeResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property int16 Volume
    {
        int16 get() { return m_value; }
    internal:
        void set(_In_ int16 value) { m_value = value; }
    }

    static VolumeGetVolumeResult^ CreateSuccessResult(_In_ int16 value)
    {
        auto result = ref new VolumeGetVolumeResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Volume = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static VolumeGetVolumeResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new VolumeGetVolumeResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    int16 m_value;
};

public ref class VolumeSetVolumeResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static VolumeSetVolumeResult^ CreateSuccessResult()
    {
        auto result = ref new VolumeSetVolumeResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static VolumeSetVolumeResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new VolumeSetVolumeResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class VolumeGetVolumeRangeResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property VolumeVolumeRange^ VolumeRange
    {
        VolumeVolumeRange^ get() { return m_value; }
    internal:
        void set(_In_ VolumeVolumeRange^ value) { m_value = value; }
    }

    static VolumeGetVolumeRangeResult^ CreateSuccessResult(_In_ VolumeVolumeRange^ value)
    {
        auto result = ref new VolumeGetVolumeRangeResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->VolumeRange = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static VolumeGetVolumeRangeResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new VolumeGetVolumeRangeResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    VolumeVolumeRange^ m_value;
};

} } } } 
